name: Cydeo Cypress Tests

on: 
   schedule: 
        # schedule ay 10:00 am Sundays
        - cron: '0 10 * * sun'

    push:
        branches:
             -main

jobs: 
     cypress-run:
     run-on: ubuntu-latest
     container: cypress/browsers:node12.18.3-chrome87-ff82
     steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Intall Dependencies
            run: npm install
          
          - name: Cypress Run
            uses: cypress-io/github-action@v4
            with:
               # since we have installed dependencies we set it false
                install: false
                browser: chrome
                spec: cypress/e2e/**/*