name: Cydeo Cypress Tests

on: 
   schedule: 
        # schedule ay 10:00 am Sundays
        - cron: '0 10 * * sun'

    push:
        branches:
             -main

jobs: 
     cypress-run:
     run-on: ubuntu-latest
     container: cypress/browser:node12.18.3-chrome87-ff82
